version: '3.1'

services:

  db:
    image: postgres
    container_name: disease-assessment-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hD[\2@XS^(-a]2SX