version: '3.1'

services:

  db:
    image: postgres
    container_name: disease-assessment-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  disease_assessment_api:
    image: vadimeladii7/disease-assessment-api:latest
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - PREDICTOR_CLIENT_URL=http://predictor:5000