create table profile
(
    id          varchar          not null
        constraint profile_pk
            primary key,
    first_name varchar not null default '',
    last_name varchar not null default '',
    email       varchar          not null unique,
    age int not null default 0,
    sex int not null default 0,
    resting_BP int not null default 0,
    cholesterol int not null default 0,
    fasting_BS int not null default 0,
    max_HR int not null default 0,
    exercise_Angina int not null default 0,
    oldpeak float not null default 0,
    chest_Pain_Type_ATA int not null default 0,
    chest_Pain_Type_NAP int not null default 0,
    chest_Pain_Type_TA int not null default 0,
    resting_ECG_Normal int not null default 0,
    resting_ECG_ST int not null default 0,
    ST_Slope_Flat int not null default 0,
    ST_Slope_Up int not null default 0,
    polyuria int not null default 0,
    polydipsia int not null default 0,
    sudden_weight_loss int not null default 0,
    weakness int not null default 0,
    polyphagia int not null default 0,
    genital_thrush int not null default 0,
    visual_blurring int not null default 0,
    itching int not null default 0,
    irritability int not null default 0,
    delayed_healing int not null default 0,
    partial_paresis int not null default 0,
    muscle_stiffness int not null default 0,
    alopecia int not null default 0,
    obesity int not null default 0
);